Update pull-request.yml

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -38,7 +38,6 @@ jobs:
           chmod +x ./.github/workflows/countline.py
           ./.github/workflows/countline.py --lines 600 --exclude_files src/types/generatedGraphQLTypes.ts tests src/typeDefs/types.ts src/constants.ts
 
-
       - name: Restore node_modules from cache
         id: cache-npm
         uses: actions/cache@v4
@@ -78,6 +77,14 @@ jobs:
 
       - name: Run Typescript Type-Checker
         run: npm run typecheck
+
+      - name: Check if the source and target branches are different
+        if: ${{ github.event.pull_request.base.ref == github.event.pull_request.head.ref }}
+        run: |
+          echo "Source Branch ${{ github.event.pull_request.head.ref }}"
+          echo "Target Branch ${{ github.event.pull_request.base.ref }}"
+          echo "Error: Source and Target Branches are the same. Please ensure they are different."
+          exit 1
 
   File-count-check:
     name: Counting files changed
