merged into develop

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -78,13 +78,13 @@ jobs:
       - name: Run Typescript Type-Checker
         run: npm run typecheck
 
-      - name: Check if the source and target branches are different
-        if: ${{ github.event.pull_request.base.ref == github.event.pull_request.head.ref }}
-        run: |
-          echo "Source Branch ${{ github.event.pull_request.head.ref }}"
-          echo "Target Branch ${{ github.event.pull_request.base.ref }}"
-          echo "Error: Source and Target Branches are the same. Please ensure they are different."
-          exit 1
+      # - name: Check if the source and target branches are different
+      #   if: ${{ github.event.pull_request.base.ref == github.event.pull_request.head.ref }}
+      #   run: |
+      #     echo "Source Branch ${{ github.event.pull_request.head.ref }}"
+      #     echo "Target Branch ${{ github.event.pull_request.base.ref }}"
+      #     echo "Error: Source and Target Branches are the same. Please ensure they are different."
+      #     exit 1
 
   File-count-check:
     name: Counting files changed
@@ -178,7 +178,7 @@ jobs:
         run: npm ci
 
       - name: Sleep for 10s
-        uses: juliangruber/sleep-action@v1
+        uses: juliangruber/sleep-action@v2
         with:
           time: 10s
 
